/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\Peterhouse JCR Merged.gltf --transform --keepmeshes --types
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GroupProps } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Windows: THREE.Mesh
    Minute_Hand: THREE.Mesh
    Hour_Hand: THREE.Mesh
    Sphere: THREE.Mesh
    Sphere_1: THREE.Mesh
    Backdrop: THREE.Mesh
  }
  materials: {
    // PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
}

const diffuseMaterial = new THREE.MeshStandardMaterial({
  color: '#d6d6d6',
})

interface ModelProps extends GroupProps {
  hourRef: React.MutableRefObject<THREE.Mesh>
  minuteRef: React.MutableRefObject<THREE.Mesh>
}

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/Peterhouse JCR Merged with Backdrop-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      {/* <mesh receiveShadow geometry={nodes.Backdrop.geometry} material={diffuseMaterial} position={[0, 3.495, 2.005]} scale={74.406} /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={diffuseMaterial}
        position={[0.024, 1.424, -0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[0.913, 0.012, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={diffuseMaterial} />
        <mesh castShadow receiveShadow geometry={nodes.Cube003_1.geometry} material={diffuseMaterial} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Windows.geometry}
        material={diffuseMaterial}
        position={[0.553, 0.508, 0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Minute_Hand.geometry}
        material={materials.PaletteMaterial002}
        position={[0, 0.991, 0.014]}
        ref={props.minuteRef}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hour_Hand.geometry}
        material={materials.PaletteMaterial002}
        position={[0, 0.991, 0.014]}
        ref={props.hourRef}
      />
      <mesh castShadow receiveShadow geometry={nodes.Sphere.geometry} material={diffuseMaterial} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere_1.geometry} material={diffuseMaterial} />
    </group>
  )
}

useGLTF.preload('/Peterhouse JCR Merged with Backdrop-transformed.glb')
